#
version: "2.4"

volumes:
  mysql_data:
  app_node_modules:
  composer_vendor:

services:
  mysql:
    image: mysql:5.7
    ports:
    # HOST PORT : CONTAINER PORT
    - ${DEMO_MYSQL_PORT:-3306}:3306
    volumes:
    # SOURCE : DESTINATION (TARGET)
    - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 3x4mpl3P455w0rd
      MYSQL_DATABASE: demo_development
      MYSQL_USER: demo
      MYSQL_PASSWORD: 3x4mpl3P455w0rd

  web:
    image: php-demo:development
    build:
      context: .
      args:
      - DEVELOPER_UID=${UID:-1000}
      - DEVELOPER_USER=${USER:-you}
    # Start mysql before starting this service:
    depends_on:
    - mysql
    volumes:
    - .:/usr/src
    - app_node_modules:/usr/src/node_modules
    - composer_vendor:/usr/src/vendor

    # Keep the stdin open, so we can attach to our app container's process
    # and do things such as byebug, etc:
    stdin_open: true

    # Enable sending signals (CTRL+C, CTRL+P + CTRL+Q) into the container:
    tty: true
